apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS QuizBattle;
    USE QuizBattle;
---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: test-mysql-deployment
    labels:
        tier: db
spec:
    replicas: 1
    minReadySeconds: 3
    selector:
        matchLabels:
            tier: db
    template:
        metadata:
            labels:
                tier: db
        spec:
            containers:
            -   image: mysql:5.7
                name: mysql
                volumeMounts:
                  - name: initdb
                    mountPath: /docker-entrypoint-initdb.d
                env:
                -   name: MYSQL_ROOT_PASSWORD
                    value: password
            volumes:
              - name: initdb
                configMap:
                  name: mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: test-db-service
spec:
  type: NodePort
  selector:
    tier: db
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32000
